# Generated by Django 5.1.4 on 2025-01-07 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='access',
            field=models.CharField(choices=[('any', 'Anyone'), ('email', 'Email required'), ('purchase_required', 'Purchase required'), ('user_required', 'User required')], default='email', max_length=20),
        ),
    ]
